### ISSUE TITLE
Does not work with @babel/core 7

### ISSUE THREAD

**Issue by ComLock** [xtuc/babel-plugin-optimize-starts-with#1]
TypeError: Property name expected type of string but got number
        at validate (SNIPPED/node_modules/@babel/types/lib/definitions/utils.js:161:13)

**Comment by xtuc** [comment]
Please provide the full output

**Comment by stevenvachon** [comment]
Same issue here:
```
> babel index.js --out-file=index-es5.js --plugins=optimize-starts-with --presets=@babel/env --source-maps

TypeError: Property name expected type of string but got number
    at validate (/project/node_modules/@babel/types/lib/definitions/utils.js:161:13)
    at Object.validate (/project/node_modules/@babel/types/lib/definitions/utils.js:172:7)
    at validate (/project/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/project/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.Identifier (/project/node_modules/@babel/types/lib/builders/generated/index.js:323:31)
    at CallExpression.splitCharCodes.map.x (/project/node_modules/babel-plugin-optimize-starts-with/lib/index.js:34:66)
    at Array.map (<anonymous>)
    at PluginPass.CallExpression (/project/node_modules/babel-plugin-optimize-starts-with/lib/index.js:34:55)
    at newFn (/project/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/project/node_modules/@babel/traverse/lib/path/context.js:53:20)
```

**Comment by xtuc** [comment]
Currently, this hasn't been tested against Babel 7. I guess some modifications are needed. Would you mind sending a PR?
